Code/MyD3/Controllers/AuthorizationController.cs
using MyD3.Core;
using System.Web.Mvc;
using MyD3.Common.Cache;
using MyD3.Common.Log;
using MyD3.Business.Interface;
using MyD3.Entity;
using DemoSite.Models;
using MyD3.Core.Security;

namespace DemoSite.Controllers
{
    /// <summary>
    /// 授权控制器
    /// </summary>
    public class AuthorizationController : BaseController
    {
        private readonly ISecurityBusiness _securityBLL;

        /// <summary>
        /// 初始化授权控制器
        /// </summary>
        /// <param name="securityBLL">安全业务对象</param>
        /// <param name="logger">日志管理</param>
        /// <param name="cacheManager">缓存管理</param>
        public AuthorizationController(ISecurityBusiness securityBLL,
            ILogger logger, ICacheManager cacheManager, IPageBusiness pageBusiness) 
            : base(logger, cacheManager, pageBusiness)
        {
            this._securityBLL = securityBLL;
        }

        /// <summary>
        /// 分组授权数据接口
        /// </summary>
        /// <param name="args">分组授权参数</param>
        /// <returns></returns>
        [HttpPost]
        [MyD3Authorize]
        public ActionResult GroupAuthoriz(AuthorizArgs args)
        {
            if (args == null)
            {
                this._logger.W("授权参数args为NULL，授权失败");
                return Json(new ResultValue<bool>(-1, "参数信息异常，无法完成授权"));
            }
            return Json(this._securityBLL.GroupAuthoriz(args.TargetID, args.Permissions, this.LoginUser.User.UserData));
        }

        /// <summary>
        /// 用户授权数据接口
        /// </summary>
        /// <param name="args">分组授权参数</param>
        /// <returns></returns>
        [HttpPost]
        [MyD3Authorize]
        public ActionResult UserAuthoriz(AuthorizArgs args)
        {
            if (args == null)
            {
                this._logger.W("授权参数args为NULL，授权失败");
                return Json(new ResultValue<bool>(-1, "参数信息异常，无法完成授权"));
            }
            return Json(this._securityBLL.UserAuthoriz(args.TargetID, args.Permissions, this.LoginUser.User.UserData));
        }

        /// <summary>
        /// 获取分组授权信息
        /// </summary>
        /// <param name="id">需要获取授权的分组编号</param>
        /// <returns></returns>
        [HttpGet]
        [MyD3Authorize]
        public ActionResult GetGroupAuthorization(string id)
        {
            this._logger.I("从业务层获取全部权限信息");
            var allPermissionResult = this._securityBLL.LoadAllModulePermission();

            if (allPermissionResult.RCode != 0)
            {
                this._logger.W("从业务层获取全部权限信息失败：" + allPermissionResult.RMsg);
                return Json(allPermissionResult, JsonRequestBehavior.AllowGet);
            }

            this._logger.I("从业务层获取目标授权");
            var targetAuthorizationResult = this._securityBLL.LoadGroupAuthorization(id);

            if (targetAuthorizationResult.RCode != 0)
            {
                this._logger.W("从业务层获取目标授权失败：" + targetAuthorizationResult.RMsg);
                return Json(targetAuthorizationResult, JsonRequestBehavior.AllowGet);
            }

            this._logger.I("开始封装返回数据");
            ResultValue<TargetAuthorizationVM> result = new ResultValue<TargetAuthorizationVM>();
            result.Data = new TargetAuthorizationVM()
            {
                AllPermissions = allPermissionResult.Data,
                TargetAuthorization = targetAuthorizationResult.Data
            };

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 获取用户授权信息
        /// </summary>
        /// <param name="id">需要获取授权的用户编号</param>
        /// <returns></returns>
        [HttpGet]
        [MyD3Authorize]
        public ActionResult GetUserAuthorization(string id)
        {
            this._logger.I("从业务层获取全部权限信息");
            var allPermissionResult = this._securityBLL.LoadAllModulePermission();

            if (allPermissionResult.RCode != 0)
            {
                this._logger.W("从业务层获取全部权限信息失败：" + allPermissionResult.RMsg);
                return Json(allPermissionResult, JsonRequestBehavior.AllowGet);
            }

            this._logger.I("从业务层获取目标授权");
            var targetAuthorizationResult = this._securityBLL.LoadUserAuthorizations(id);

            if (targetAuthorizationResult.RCode != 0)
            {
                this._logger.W("从业务层获取目标授权失败：" + targetAuthorizationResult.RMsg);
                return Json(targetAuthorizationResult, JsonRequestBehavior.AllowGet);
            }

            this._logger.I("开始封装返回数据");
            ResultValue<TargetAuthorizationVM> result = new ResultValue<TargetAuthorizationVM>();
            result.Data = new TargetAuthorizationVM()
            {
                AllPermissions = allPermissionResult.Data,
                TargetAuthorization = targetAuthorizationResult.Data
            };

            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

Code/MyD3/Controllers/GroupController.cs
using DemoSite.Models;
using MyD3.Business.Interface;
using MyD3.Common.Cache;
using MyD3.Common.Log;
using MyD3.Core;
using MyD3.Core.Security;
using MyD3.Entity;
using MyD3.Entity.DBEntity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DemoSite.Controllers
{
    public class GroupController : BaseController
    {
        private readonly IGroupBusiness _groupBLL;
        private readonly IUserBusiness _userBLL;

        /// <summary>
        /// 初始化分组控制器
        /// </summary>
        /// <param name="groupBLL"></param>
        /// <param name="logger"></param>
        /// <param name="cacheManager"></param>
        public GroupController(IGroupBusiness groupBLL, IUserBusiness userBLL,
            ILogger logger, ICacheManager cacheManager, IPageBusiness pageBusiness)
            : base(logger, cacheManager, pageBusiness)
        {
            this._groupBLL = groupBLL;
            this._userBLL = userBLL;
        }

        /// <summary>
        /// 打开分组管理界面
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [MyD3Authorize]
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 根据ID获取分组信息对象
        /// </summary>
        /// <param name="id">分组系统编号</param>
        /// <returns>分组信息JSON</returns>
        [HttpGet]
        [MyD3Authorize]
        public ActionResult Get(string id)
        {
            return Json(this._groupBLL.Get(id), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 新增分组信息
        /// </summary>
        /// <param name="model">需要新增的分组对象</param>
        /// <returns></returns>
        [HttpPost]
        [MyD3Authorize]
        public ActionResult Post(Group model)
        {
            //调用业务层进行处理
            return Json(this._groupBLL.Save(model, base.LoginUser.User.UserData));
        }

        /// <summary>
        /// 新增分组信息
        /// </summary>
        /// <param name="model">需要新增的分组对象</param>
        /// <returns></returns>
        [HttpPut]
        [MyD3Authorize]
        public ActionResult Put(Group model)
        {
            //调用业务层进行处理
            return Json(this._groupBLL.Save(model, base.LoginUser.User.UserData));
        }

        /// <summary>
        /// 删除分组
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpDelete]
        [MyD3Authorize]
        public ActionResult Delete(Group model)
        {
            //调用业务层进行处理
            return Json(this._groupBLL.Delete(model, base.LoginUser.User.UserData));
        }

        /// <summary>
        /// 搜索分组信息
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [MyD3Authorize]
        public ActionResult Search()
        {
            this._logger.I("开始分组搜索，分析搜索条件");
            var searchArgs = this.GetRequestSearchArgs<Group>(this.Request);

            this._logger.I("搜索条件分析完毕，开始调用业务层进行搜索");
            var searchResult = this._groupBLL.Search(searchArgs);

            this._logger.I("搜索执行完毕，执行结果：" + searchResult);
            return Json(searchResult.Data);
        }

        /// <summary>
        /// 获取分组下的全部成员
        /// </summary>
        /// <param name="id">分组编号</param>
        /// <returns></returns>
        [HttpGet]
        [MyD3Authorize]
        public ActionResult GetGroupMembers(string id)
        {
            //直接从业务层获取
            return Json(this._userBLL.GetGroupMembers(id), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 设置分组成员
        /// </summary>
        /// <param name="args">设置分组成员参数对象</param>
        /// <returns></returns>
        [HttpPost]
        [MyD3Authorize]
        public ActionResult SetGroupMember(SetGroupMembersArgs args)
        {
            if (args == null)
            {
                this._logger.W("参数args为NULL，授权失败");
                return Json(new ResultValue<bool>(-1, "信息异常，无法完成授权"));
            }
            //直接从业务层处理
            return Json(this._groupBLL.SetGroupMember(args.GroupID, args.UserIDList, this.LoginUser.User.UserData));
        }
    }
}

Code/MyD3/Controllers/UserController.cs
using MyD3.Business.Interface;
using MyD3.Common.Cache;
using MyD3.Common.Log;
using MyD3.Core;
using MyD3.Core.Security;
using MyD3.Entity.DBEntity;
using System.Web.Mvc;

namespace DemoSite.Controllers
{
    public class UserController : BaseController
    {
        private readonly IUserBusiness _userBLL;

        public UserController(IUserBusiness userBLL, ILogger logger, ICacheManager cacheManager, IPageBusiness pageBusiness)
            : base(logger, cacheManager, pageBusiness)
        {
            this._userBLL = userBLL;
        }

        /// <summary>
        /// 查看用户管理页面
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [MyD3Authorize]
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 根据ID获取用户信息对象
        /// </summary>
        /// <param name="id">用户系统编号</param>
        /// <returns>用户信息JSON</returns>
        [HttpGet]
        [MyD3Authorize]
        public ActionResult Get(string id)
        {
            return Json(this._userBLL.Get(id), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 新增用户信息
        /// </summary>
        /// <param name="model">需要新增的用户对象</param>
        /// <returns></returns>
        [HttpPost]
        [MyD3Authorize]
        public ActionResult Post(User model)
        {
            //调用业务层进行处理
            return Json(this._userBLL.Save(model, base.LoginUser.User.UserData));
        }

        /// <summary>
        /// 新增用户信息
        /// </summary>
        /// <param name="model">需要新增的用户对象</param>
        /// <returns></returns>
        [HttpPut]
        [MyD3Authorize]
        public ActionResult Put(User model)
        {
            //调用业务层进行处理
            return Json(this._userBLL.Save(model, base.LoginUser.User.UserData));
        }

        /// <summary>
        /// 删除用户
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpDelete]
        [MyD3Authorize]
        public ActionResult Delete(User model)
        {
            //调用业务层进行处理
            return Json(this._userBLL.Delete(model, base.LoginUser.User.UserData));
        }

        /// <summary>
        /// 搜索用户信息
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [MyD3Authorize]
        public ActionResult Search()
        {
            this._logger.I("开始用户搜索，分析搜索条件");
            var searchArgs = this.GetRequestSearchArgs<User>(this.Request);

            this._logger.I("搜索条件分析完毕，开始调用业务层进行搜索");
            var searchResult = this._userBLL.Search(searchArgs);

            this._logger.I("搜索执行完毕，执行结果：" + searchResult);
            return Json(searchResult.Data);
        }
    }
}

Code/MyD3/Views/Group/GroupEditPartial.cshtml
<script type="text/x-jsrender" id="group_edit_modal">
    <div class="modal fade group_model" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">
                        {{if !ID}}
                        新建分组
                        {{else}}
                        编辑分组 - {{: Name}}
                        {{/if}}
                    </h4>
                </div>
                <form id="group_form">
                    <div class="modal-body">
                        <input type="hidden" name="ID" value="{{:ID}}" />
                        <div class="form-group fg-float">
                            <div class="fg-line">
                                <input type="text" name="Name" value="{{>Name}}" maxlength="25" class="input-sm form-control fg-input" />
                            </div>
                            <label class="fg-label">分组名*</label>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" data-dismiss="modal" class="btn btn-default">关闭</button>
                        <button type="submit" id="save" class="btn btn-primary {{if !ID}}bgm-green{{/if}}">保存</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</script>

<!-- 编辑对话框相关脚本 -->
<script type="text/javascript" id="edit_dialog">
    function init_form_validator(target_form) {
        target_form.validate({
            errorElement: 'div',
            errorClass: 'help-block',
            focusInvalid: true,
            rules: {
                Name: {
                    required: true,
                    minlength: 2
                }
            },
            messages: {
                Name: {
                    required: "分组名不能为空",
                    minlength: "分组名至少需要2位",
                }
            },
            highlight: function (e) {
                $(e).closest('.form-group').addClass('has-error');
            },
            success: function (e) {
                $(e).closest('.form-group').removeClass('has-error');
                $(e).remove();
            },
            errorPlacement: function (error, element) {
                error.insertAfter(element.parent());
            }
        });
    }

    function init_ajax_form(target_form, action, method) {
        /* ===================== 初始化Form =========================*/
        target_form.ajaxForm({
            url: action,
            type: method,
            dataType: 'json',
            contentType: "application/x-www-form-urlencoded; charset=utf-8",
            beforeSerialize: function (form, options) {
                //序列化前先调用validation控件进行验证
                return $(form).valid();
            },
            beforeSubmit: function (data, form, options) {
                //防止重复提交，禁用提交按钮
                $('#group_form button:submit').text("正在处理");
                $('#group_form button:submit').attr('disabled', 'disabled');
                $('#group_form input').attr('disabled', 'disabled');
            },
            success: function (result) {
                //开放控件
                $('#group_form button:submit').text("保存");
                $('#group_form button:submit').removeAttr('disabled');
                $('#group_form input').removeAttr('disabled');

                if (result.RCode == 0) {
                    $(".group_model").modal("hide");
                    $("#data-table-command").bootgrid("reload");
                    swal({
                        title: "成功",
                        text: "新分组保存成功",
                        type: "success",
                        showConfirmButton: false,
                        timer: 2000
                    });
                } else {
                    swal({
                        title: "失败",
                        text: result.RMsg,
                        type: "error",
                        showConfirmButton: false,
                        timer: 2000
                    });
                }
            },
            error: function (result) {
                //开放控件
                $('#group_form button:submit').text("保存");
                $('#group_form button:submit').removeAttr('disabled');
                $('#group_form input').removeAttr('disabled');
                swal({
                    title: "失败",
                    text: decodeURI(result.getResponseHeader("statusText")),
                    type: "error",
                    showConfirmButton: false,
                    timer: 2000
                });
            }
        });
    }

    /**
     * 以新增方式打开
     */
    function dialog_new() {
        var modal_html = $($("#group_edit_modal").render({
            ID: null,
            Name: null
        }));

        set_dialog_attr(modal_html, "#group_form", "@Url.Action("Post", "Group")", "post");
    }
    /**
     * 以编辑方式打开
     */
    function dialog_edit(group_id) {
        jackTool.tools.net.get('@Url.Action("Get", "Group")' + '/' + group_id, function (result) {
            if (result.RCode == 0) {
                var data = {
                    ID: result.Data.ID,
                    Name: result.Data.Name
                };

                var modal_html = $($("#group_edit_modal").render(data));

                set_dialog_attr(modal_html, "#group_form", "@Url.Action("Put", "Group")", "put");
            } else {
                swal({
                    title: "失败",
                    text: result.RMsg,
                    type: "error",
                    showConfirmButton: false,
                    timer: 2000
                });
            }
        });
    }

    /**
     * 为对话框中的内容提供初始值设定
     */
    function set_dialog_attr(dialog, form_selector, form_action, form_method) {
        //清除上一次残留数据
        $(".group_model").remove();

        //设置Dialog不会在点击其他地方时被关闭
        dialog.modal({
            backdrop: "static"
        });

        //初始化表单相关内容
        var form = dialog.find(form_selector);
        //初始化表单验证
        init_form_validator(form);
        //初始化表单
        init_ajax_form(form, form_action, form_method);
        //初始化悬浮输入框LABLE
        jackTool.tools.view.build_fg_input(dialog);
    }
</script>

Code/MyD3/Views/Group/GroupMemberPartial.cshtml
<script type="text/x-jsrender" id="members_modal">
    <div class="modal fade members_model" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">
                        成员管理
                    </h4>
                </div>
                <div class="modal-body">
                    <table id="members-table" class="table table-striped table-vmiddle">
                        <thead>
                            <tr>
                                <th data-column-id="ID" data-identifier="true" data-visible="false">系统编号</th>
                                <th data-column-id="LoginName" data-sortable="true">用户名</th>
                                <th data-column-id="DisplayName" data-sortable="true">显示名</th>
                                <th data-column-id="CreateDate" data-formatter="datetime" data-sortable="true">注册时间</th>
                            </tr>
                        </thead>
                    </table>
                </div>
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" class="btn btn-default">关闭</button>
                    <button type="button" id="save_member" class="btn btn-primary" data-group-id="{{>ID}}" }>保存</button>
                </div>
            </div>
        </div>
    </div>
</script>

<script type="text/javascript" id="members_script">
    /**
    * 打开成员对话框
    */
    function dialog_members(group_id) {
        //从服务器获取分组授权信息
        jackTool.tools.net.get("@Url.Action("GetGroupMembers", "Group")" + "/" + group_id, function (result) {
            if (result && result.RCode == 0) {
                var modal_html = $($("#members_modal").render({ ID: group_id }));

                set_member_dialog_attr(modal_html, result.Data);
            } else {
                swal({
                    title: "失败",
                    text: result ? result.RMsg : "获取分组成员信息失败",
                    type: "error",
                    showConfirmButton: false,
                    timer: 2000
                });
            }
        });
    }

    /**
     * 为对话框中的内容提供初始值设定
     */
    function set_member_dialog_attr(dialog, memberData) {
        //清除上一次残留数据
        $(".members_model").remove();

        //设置Dialog不会在点击其他地方时被关闭
        dialog.modal({
            backdrop: "static"
        });

        //初始化BootGrid
        dialog.find("#members-table").bootgrid({
            ajax: true,
            url: '@Url.Action("Search", "User")',
            post: function () {
                return {

                };
            },
            selection: true,
            multiSelect: true,
            keepSelection: true,
            css: {
                icon: 'zmdi icon',
                iconColumns: 'zmdi-view-module',
                iconDown: 'zmdi-expand-more',
                iconRefresh: 'zmdi-refresh',
                iconUp: 'zmdi-expand-less'
            },
            labels: {
                all: "全部",
                infos: "显示 {{ctx.start}} 到 {{ctx.end}} 条 共 {{ctx.total}} 条结果",
                loading: "查询中...",
                noResults: "没有符合套件的结果",
                refresh: "刷新",
                search: "搜索"
            },
            formatters: {
                "datetime": function (column, row) {
                    var value = moment(row.CreateDate);
                    return value.format("YYYY-MM-DD HH:mm:ss");
                },
            }
        }).on("loaded.rs.jquery.bootgrid", function (e) {
            //使用underscore将所有已授权的权限ID提取成数组
            var groupMemberIDList = _.map(memberData, function (data) {
                return data.ID;
            });

            $(this).bootgrid("select", groupMemberIDList);
        });

        dialog.find("#save_member").on("click", btnSaveMember_click);
    }

    /**
    * 保存分组成员
    */
    function btnSaveMember_click(e) {
        //获取已选择的所有权限
        var selected = $(".members_model #members-table").bootgrid("getSelectedRows");
        //获取需要授权的目标对象
        var group_id = $(this).data("group-id");

        //禁用按钮处理
        $('.members_model #save_member').text("正在处理");
        $('.members_model #save_member').attr('disabled', 'disabled');
        $('.members_model input').attr('disabled', 'disabled');
        swal({
            title: "处理中",
            text: "请稍后......",
            type: "info",
            showConfirmButton: false,
        })

        //POST数据到服务器进行设置
        jackTool.tools.net.post("@Url.Action("SetGroupMember", "Group")", { GroupID: group_id, UserIDList: selected },
            function (result) {
                if (!result || result.RCode != 0) {
                    $('.members_model #save_member').text("保存");
                    $('.members_model #save_member').removeAttr('disabled');
                    $('.members_model input').removeAttr('disabled');
                    return swal({
                        title: "失败",
                        text: result ? result.RMsg : "设置失败",
                        type: "error",
                        showConfirmButton: false,
                        timer: 2000
                    });
                }
                $(".members_model").modal("hide");
                swal({
                    title: "成功",
                    text: "成员列表保存成功",
                    type: "success",
                    showConfirmButton: false,
                    timer: 2000
                });
            });
    }
</script>

Code/MyD3/Views/Group/Index.cshtml
@{
    ViewBag.Module = "分组管理";
    ViewBag.Title = "分组列表";
    ViewBag.Desceiption = "维护系统中的分组，包括基本信息，状态，授权，人员等等";
    Layout = "~/Views/Shared/Base/_Layout.cshtml";
}

@section button_list{
    <button class="btn btn-success btn-icon-text btn-add-group">
        <i class="zmdi zmdi-plus"></i>
        新增分组
    </button>
}

<script type="text/x-jsrender" id="cmd-tpl">
    <button type='button' class='btn btn-sm bgm-cyan btn-icon command-edit' title="编辑" data-row-id='{{>ID}}' data-row-name='{{>Name}}'><span class='zmdi zmdi-edit'></span></button>
    <button type='button' class='btn btn-sm bgm-green btn-icon command-authoriz' title="授权管理" data-row-id='{{>ID}}' data-row-name='{{>Name}}'><span class='zmdi zmdi-key'></span></button>
    <button type='button' class='btn btn-sm bgm-green btn-icon command-members' title="成员管理" data-row-id='{{>ID}}' data-row-name='{{>Name}}'><span class='zmdi zmdi-accounts'></span></button>
    <button type='button' class='btn btn-sm bgm-red btn-icon command-delete' title="删除" data-row-id='{{>ID}}' data-row-name='{{>Name}}'><span class='zmdi zmdi-delete'></span></button>
</script>

<table id="data-table-command" class="table table-striped table-vmiddle">
    <thead>
        <tr>
            <th data-column-id="ID" data-identifier="true" data-visible="false">系统编号</th>
            <th data-column-id="Name" data-sortable="true">名称</th>
            <th data-column-id="CreateDate" data-formatter="datetime" data-sortable="true">创建时间</th>
            <th data-column-id="commands" data-formatter="commands" data-sortable="false">操作</th>
        </tr>
    </thead>
</table>

@section scripts{
    <!-- Data Table -->
    <script type="text/javascript">
        $(function () {
            $(".btn-add-group").on("click", btnAddGroup_click);

            $("#data-table-command").bootgrid({
                ajax: true,
                url: '@Url.Action("Search")',
                post: function () {
                    return {

                    };
                },
                css: {
                    icon: 'zmdi icon',
                    iconColumns: 'zmdi-view-module',
                    iconDown: 'zmdi-expand-more',
                    iconRefresh: 'zmdi-refresh',
                    iconUp: 'zmdi-expand-less'
                },
                labels: {
                    all: "全部",
                    infos: "显示 {{ctx.start}} 到 {{ctx.end}} 条 共 {{ctx.total}} 条结果",
                    loading: "查询中...",
                    noResults: "没有符合套件的结果",
                    refresh: "刷新",
                    search: "搜索"
                },
                formatters: {
                    "commands": function (column, row) {
                        var args = {
                            ID: row.ID,
                            Name: row.Name
                        };

                        return $("#cmd-tpl").render(args);
                    },
                    "datetime": function (column, row) {
                        var value = moment(row.CreateDate);
                        return value.format("YYYY-MM-DD HH:mm:ss");
                    },
                }
            }).on("loaded.rs.jquery.bootgrid", function () {
                $(this).find(".command-edit").on("click", btnEditGroup_click)
                .end().find(".command-delete").on("click", btnDeleteGroup_click)
                .end().find(".command-authoriz").on("click", btnAuthoriz_click)
                .end().find(".command-members").on("click", btnMembers_click);

                //权限处理
                jackTool.security.parse();
            });
        });

        /**
        * 新增分组按钮点击事件
        */
        function btnAddGroup_click(e) {
            //以新增方式打开
            dialog_new();
        }

        /**
        * 分组授权按钮点击事件
        */
        function btnAuthoriz_click(e) {
            var group_id = $(this).data("row-id");

            //从服务器获取分组授权信息
            jackTool.tools.net.get("@Url.Action("GetGroupAuthorization", "Authorization")" + "/" + group_id, function (result) {
                if (result && result.RCode == 0) {
                    //注入ID属性
                    result.Data.ID = group_id;

                    //调用AuthorizationPartialPage中的方法打开对话框进行授权
                    dialog_authoriz(result.Data, "@Url.Action("GroupAuthoriz", "Authorization")");
                } else {
                    swal({
                        title: "失败",
                        text: result ? result.RMsg : "获取授权信息失败",
                        type: "error",
                        showConfirmButton: false,
                        timer: 2000
                    });
                }
            });
        }

        /**
        * 编辑分组按钮点击事件
        */
        function btnEditGroup_click(e) {
            var group_id = $(this).data("row-id");
            dialog_edit(group_id);
        }

        /**
        * 分组成员按钮点击事件
        */
        function btnMembers_click(e) {
            var group_id = $(this).data("row-id");
            dialog_members(group_id);
        }

        /**
        * 删除分组按钮点击事件
        */
        function btnDeleteGroup_click(e) {
            var group_name = $(this).data("row-name");
            var group_id = $(this).data("row-id");

            swal({
                title: "请确认",
                text: "确定要删除该分组 " + group_name + " 么？",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "删除!",
                cancelButtonText: "返回",
                closeOnConfirm: false,
                closeOnCancel: true
            }, function (isConfirm) {
                if (isConfirm) {
                    jackTool.tools.net.delete("@Url.Action("Delete")", { ID: group_id }, function (result) {
                        if (!result || result.RCode != 0) {
                            swal({
                                title: "删除失败",
                                text: result.RMsg,
                                type: "error",
                                showConfirmButton: false,
                                timer: 2000
                            });
                        } else {
                            swal({
                                title: "成功",
                                text: "分组删除成功",
                                type: "success",
                                showConfirmButton: false,
                                timer: 2000
                            });
                            $("#data-table-command").bootgrid("reload");
                        }
                    });
                }
            });
        }
    </script>
}

@Html.Partial("~/Views/Shared/Security/AuthorizationPartialPage.cshtml")
@Html.Partial("~/Views/Group/GroupEditPartial.cshtml")
@Html.Partial("~/Views/Group/GroupMemberPartial.cshtml")