Code/MyD3/Controllers/DictionaryController.cs
using MyD3.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyD3.Common.Cache;
using MyD3.Common.Log;
using MyD3.Core.Security;
using MyD3.Entity.DBEntity;
using MyD3.Business.Interface;
using MyD3.Business.Interface.DataModel;

namespace DemoSite.Controllers
{
    public class DictionaryController : BaseController
    {
        private readonly IDictionaryBusiness _dictionaryBLL;

        public DictionaryController(IDictionaryBusiness dictionaryBLL,
            ILogger logger, ICacheManager cacheManager, IPageBusiness pageBusiness)
            : base(logger, cacheManager, pageBusiness)
        {
            this._dictionaryBLL = dictionaryBLL;
        }

        [HttpGet]
        [MyD3Authorize]
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 禁用指定的索引
        /// </summary>
        /// <param name="id">需要禁用的索引ID</param>
        /// <returns></returns>
        [HttpGet]
        [MyD3Authorize]
        public ActionResult Disable(string id)
        {
            return Json(this._dictionaryBLL.Disable(id, this.LoginUser.User.UserData), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 启用指定的索引
        /// </summary>
        /// <param name="id">需要启用的索引ID</param>
        /// <returns></returns>
        [HttpGet]
        [MyD3Authorize]
        public ActionResult Enable(string id)
        {
            return Json(this._dictionaryBLL.Enable(id, this.LoginUser.User.UserData), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 新增字典数据
        /// </summary>
        /// <param name="model">需要新增的字段数据信息</param>
        /// <returns></returns>
        [HttpPost]
        [MyD3Authorize]
        public ActionResult Post(DictionaryStruct model)
        {
            //直接业务层返回
            return Json(this._dictionaryBLL.Save(model, base.LoginUser.User.UserData));
        }

        /// <summary>
        /// 修改字典数据
        /// </summary>
        /// <param name="model">需要修改的字段数据信息</param>
        /// <returns></returns>
        [HttpPut]
        [MyD3Authorize]
        public ActionResult Put(DictionaryStruct model)
        {
            //直接业务层返回
            return Json(this._dictionaryBLL.Save(model, base.LoginUser.User.UserData));
        }

        /// <summary>
        /// 根据ID获取指定的数据字典结构化数据
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        [MyD3Authorize]
        public ActionResult Get(string id)
        {
            //从业务层返回
            return Json(this._dictionaryBLL.GetStruct(id), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 搜索字典索引信息
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [MyD3Authorize]
        public ActionResult Search()
        {
            this._logger.I("开始索引搜索，分析搜索条件");
            var searchArgs = this.GetRequestSearchArgs<DictionaryIndex>(this.Request);

            this._logger.I("搜索条件分析完毕，开始调用业务层进行搜索");
            var searchResult = this._dictionaryBLL.Search(searchArgs);

            this._logger.I("搜索执行完毕，执行结果：" + searchResult);
            return Json(searchResult.Data);
        }
    }
}

Code/MyD3/Controllers/GroupController.cs
using DemoSite.Models;
using MyD3.Business.Interface;
using MyD3.Common.Cache;
using MyD3.Common.Log;
using MyD3.Core;
using MyD3.Core.Security;
using MyD3.Entity;
using MyD3.Entity.DBEntity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DemoSite.Controllers
{
    public class GroupController : BaseController
    {
        private readonly IGroupBusiness _groupBLL;
        private readonly IUserBusiness _userBLL;

        /// <summary>
        /// 初始化分组控制器
        /// </summary>
        /// <param name="groupBLL"></param>
        /// <param name="logger"></param>
        /// <param name="cacheManager"></param>
        public GroupController(IGroupBusiness groupBLL, IUserBusiness userBLL,
            ILogger logger, ICacheManager cacheManager, IPageBusiness pageBusiness)
            : base(logger, cacheManager, pageBusiness)
        {
            this._groupBLL = groupBLL;
            this._userBLL = userBLL;
        }

        /// <summary>
        /// 打开分组管理界面
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [MyD3Authorize]
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 根据ID获取分组信息对象
        /// </summary>
        /// <param name="id">分组系统编号</param>
        /// <returns>分组信息JSON</returns>
        [HttpGet]
        [MyD3Authorize]
        public ActionResult Get(string id)
        {
            return Json(this._groupBLL.Get(id), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 新增分组信息
        /// </summary>
        /// <param name="model">需要新增的分组对象</param>
        /// <returns></returns>
        [HttpPost]
        [MyD3Authorize]
        public ActionResult Post(Group model)
        {
            //调用业务层进行处理
            return Json(this._groupBLL.Save(model, base.LoginUser.User.UserData));
        }

        /// <summary>
        /// 新增分组信息
        /// </summary>
        /// <param name="model">需要新增的分组对象</param>
        /// <returns></returns>
        [HttpPut]
        [MyD3Authorize]
        public ActionResult Put(Group model)
        {
            //调用业务层进行处理
            return Json(this._groupBLL.Save(model, base.LoginUser.User.UserData));
        }

        /// <summary>
        /// 删除分组
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpDelete]
        [MyD3Authorize]
        public ActionResult Delete(Group model)
        {
            //调用业务层进行处理
            return Json(this._groupBLL.Delete(model, base.LoginUser.User.UserData));
        }

        /// <summary>
        /// 搜索分组信息
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [MyD3Authorize]
        public ActionResult Search()
        {
            this._logger.I("开始分组搜索，分析搜索条件");
            var searchArgs = this.GetRequestSearchArgs<Group>(this.Request);

            this._logger.I("搜索条件分析完毕，开始调用业务层进行搜索");
            var searchResult = this._groupBLL.Search(searchArgs);

            this._logger.I("搜索执行完毕，执行结果：" + searchResult);
            return Json(searchResult.Data);
        }

        /// <summary>
        /// 获取分组下的全部成员
        /// </summary>
        /// <param name="id">分组编号</param>
        /// <returns></returns>
        [HttpGet]
        [MyD3Authorize]
        public ActionResult GetGroupMembers(string id)
        {
            //直接从业务层获取
            return Json(this._userBLL.GetGroupMembers(id), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 设置分组成员
        /// </summary>
        /// <param name="args">设置分组成员参数对象</param>
        /// <returns></returns>
        [HttpPost]
        [MyD3Authorize]
        public ActionResult SetGroupMember(SetGroupMembersArgs args)
        {
            if (args == null)
            {
                this._logger.W("参数args为NULL，授权失败");
                return Json(new ResultValue<bool>(-1, "信息异常，无法完成授权"));
            }
            //直接从业务层处理
            return Json(this._groupBLL.SetGroupMember(args.GroupID, args.UserIDList, this.LoginUser.User.UserData));
        }
    }
}

Code/MyD3/Controllers/SystemSettingController.cs
using MyD3.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyD3.Common.Cache;
using MyD3.Common.Log;
using MyD3.Business.Interface;
using DemoSite.Models;
using MyD3.Entity;
using MyD3.Entity.DBEntity;
using MyD3.Entity.DBView;
using MyD3.Core.Security;

namespace DemoSite.Controllers
{
    public class SystemSettingController : BaseController
    {
        private readonly ISystemSettingBusiness _sysSettingBLL;
        private readonly IDictionaryBusiness _dictionaryBLL;

        public SystemSettingController(ISystemSettingBusiness sysSettingBLL, IDictionaryBusiness dictionaryBLL,
            ILogger logger, ICacheManager cacheManager, IPageBusiness pageBusiness)
            : base(logger, cacheManager, pageBusiness)
        {
            this._sysSettingBLL = sysSettingBLL;
            this._dictionaryBLL = dictionaryBLL;
        }

        [HttpGet]
        [MyD3Authorize]
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 获取系统设置视图数据
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [MyD3Authorize]
        public ActionResult All()
        {
            this._logger.I("开始获取全部的设置数据");
            var allSettingResult = this._sysSettingBLL.AllSystemSettingDetail();

            if (allSettingResult.RCode != 0)
            {
                this._logger.W("获取全部设置数据失败，无法加载设置视图数据");
                return Json(allSettingResult);
            }

            this._logger.I("开始获取所有相关联的数据字典值");
            allSettingResult.Data.Where(x => x.ValueType == "OPTION" && x.OptionType == 1).ToList().ForEach(delegate (SystemSettingDetail x)
           {
               if (string.IsNullOrEmpty(x.OptionValue))
               {
                   this._logger.W("由于缺少关联数据字典表的编号，获取配置数据失败了：" + x.Name);
                   throw new ArgumentException("缺少关联数据字典表的编号");
               }

               //获取相关的数据字典值
               var dictionaryDataDetail = this._dictionaryBLL.GetStruct(x.OptionValue);

               if (dictionaryDataDetail.RCode != 0)
               {
                   this._logger.W("从数据库获取字典数据失败：" + dictionaryDataDetail);
                   throw new Exception("从数据库获取字典数据失败");
               }

               x.OptionValue = string.Join(",", dictionaryDataDetail.Data.Data.OrderBy(y => y.OrderNo).Select(y => y.Value).ToArray());
               x.OptionText = string.Join(",", dictionaryDataDetail.Data.Data.OrderBy(y => y.OrderNo).Select(y => y.Name).ToArray());
           });

            //组装数据
            SysSettingIndexVM result = new SysSettingIndexVM();
            result.SettingGroups = allSettingResult.Data.GroupBy(x => x.GroupID, y => y).Select(x => new SysSettingIndexGroupVM()
            {
                GroupID = x.ToList()[0].GroupID,
                GroupName = x.ToList()[0].GroupName,
                OrderNo = x.ToList()[0].GroupOrderNo,
                Settings = x.Where(y => y.GroupID == x.Key).OrderBy(y => y.OrderNo).ToArray()
            }).OrderBy(x => x.OrderNo).ToArray();

            return Json(new ResultValue<SysSettingIndexVM>(result), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 更新系统设置
        /// </summary>
        /// <param name="args">系统配置页面参数</param>
        /// <returns></returns>
        [HttpPut]
        [MyD3Authorize]
        public ActionResult Put(SaveSystemSettingArgs[] args)
        {
            //直接从业务层返回
            return Json(this._sysSettingBLL.Save(args.ToDictionary(x => x.Name, y => y.Value), base.LoginUser.User.UserData));
        }
    }
}

Code/MyD3/Controllers/UserController.cs
using MyD3.Business.Interface;
using MyD3.Common.Cache;
using MyD3.Common.Log;
using MyD3.Core;
using MyD3.Core.Security;
using MyD3.Entity.DBEntity;
using System.Web.Mvc;

namespace DemoSite.Controllers
{
    public class UserController : BaseController
    {
        private readonly IUserBusiness _userBLL;

        public UserController(IUserBusiness userBLL, ILogger logger, ICacheManager cacheManager, IPageBusiness pageBusiness)
            : base(logger, cacheManager, pageBusiness)
        {
            this._userBLL = userBLL;
        }

        /// <summary>
        /// 查看用户管理页面
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [MyD3Authorize]
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 根据ID获取用户信息对象
        /// </summary>
        /// <param name="id">用户系统编号</param>
        /// <returns>用户信息JSON</returns>
        [HttpGet]
        [MyD3Authorize]
        public ActionResult Get(string id)
        {
            return Json(this._userBLL.Get(id), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 新增用户信息
        /// </summary>
        /// <param name="model">需要新增的用户对象</param>
        /// <returns></returns>
        [HttpPost]
        [MyD3Authorize]
        public ActionResult Post(User model)
        {
            //调用业务层进行处理
            return Json(this._userBLL.Save(model, base.LoginUser.User.UserData));
        }

        /// <summary>
        /// 新增用户信息
        /// </summary>
        /// <param name="model">需要新增的用户对象</param>
        /// <returns></returns>
        [HttpPut]
        [MyD3Authorize]
        public ActionResult Put(User model)
        {
            //调用业务层进行处理
            return Json(this._userBLL.Save(model, base.LoginUser.User.UserData));
        }

        /// <summary>
        /// 删除用户
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpDelete]
        [MyD3Authorize]
        public ActionResult Delete(User model)
        {
            //调用业务层进行处理
            return Json(this._userBLL.Delete(model, base.LoginUser.User.UserData));
        }

        /// <summary>
        /// 搜索用户信息
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [MyD3Authorize]
        public ActionResult Search()
        {
            this._logger.I("开始用户搜索，分析搜索条件");
            var searchArgs = this.GetRequestSearchArgs<User>(this.Request);

            this._logger.I("搜索条件分析完毕，开始调用业务层进行搜索");
            var searchResult = this._userBLL.Search(searchArgs);

            this._logger.I("搜索执行完毕，执行结果：" + searchResult);
            return Json(searchResult.Data);
        }
    }
}

Code/MyD3/Views/Shared/Base/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="pragma" content="no-cache">
    <meta http-equiv="cache-control" content="no-cache">
    <meta http-equiv="expires" content="0">   
    <title>@ViewBag.Title</title>
    @Styles.Render("~/bundles/Components/style")
    @Styles.Render("~/bundles/Components/style/app1")
    @Styles.Render("~/bundles/Components/style/app2")
    @Styles.Render("~/bundles/site/styles")
    @RenderSection("style", required: false)
</head>
<body>
    @Html.Partial("~/Views/Shared/Base/_LayoutHeaderPartial.cshtml");

    <section id="main">
        <aside id="sidebar">
            <div class="sidebar-inner c-overflow">
                @Html.Partial("~/Views/Shared/Base/_LayoutProfileMenuPartial.cshtml");

                @Html.Partial("~/Views/Shared/Base/_LayoutSideMenuPartial.cshtml");
            </div>
        </aside>
        <section id="content">
            <div class="container">
                <div class="block-header">
                    <h2>@ViewBag.Module</h2>
                </div>
                <div class="card">
                    <div class="card-header">
                        <h2>@ViewBag.Title <small>@ViewBag.Desceiption</small></h2>
                    </div>
                    <div class="button-list">
                        @RenderSection("button_list", required: false)
                    </div>
                    <div class="card-body card-padding">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </section>
    </section>

    @Html.Partial("~/Views/Shared/Base/_LayoutFootPartial.cshtml");

    @Scripts.Render("~/bundles/Components/Base")
    @Scripts.Render("~/bundles/Components/nicescroll")
    @Scripts.Render("~/bundles/Components/Waves")
    @Scripts.Render("~/bundles/Components/bootstrap-growl")
    @Scripts.Render("~/bundles/Components/SweetAlert")
    @Scripts.Render("~/bundles/Components/bootgrid");
    @Scripts.Render("~/bundles/Components/bootstrap-select");
    @*此处需要注意，jackTool库需要在DateTimePick之前初始化，以便设置Moment*@
    @Scripts.Render("~/bundles/jack-tool")
    @Scripts.Render("~/bundles/Components/datetimePicker");
    @RenderSection("scripts", required: false)

    <script type="text/javascript">
        $(function () {
            //设置用户名称到用户信息区域
            $(".login-user-name").html(jackTool.logininfo.getUserName());

            //设置当前路由信息
            jackTool.tools.url.set("@ViewContext.RouteData.Values["area"]",
                "@ViewContext.RouteData.Values["controller"]",
                "@ViewContext.RouteData.Values["action"]");
            //设置当前页面TreePath
            jackTool.tools.url.setPageTreePath("@ViewBag.PageTreePath");

            //权限处理
            jackTool.security.parse();
        });
    </script>
</body>
</html>

Code/MyD3/Views/Shared/Base/_LayoutFootPartial.cshtml
<footer id="footer">
    Copyright &copy; 2016 Dipper Star

    <ul class="f-menu">
        <li><a href="">首页</a></li>
        <li><a href="">预览</a></li>
        <li><a href="">报表</a></li>
        <li><a href="">支持</a></li>
        <li><a href="">联系我们</a></li>
    </ul>
</footer>

Code/MyD3/Views/Shared/Base/_LayoutHeaderPartial.cshtml
<header id="header">
    <ul class="header-inner">
        <li id="menu-trigger" data-trigger="#sidebar">
            <div class="line-wrap">
                <div class="line top"></div>
                <div class="line center"></div>
                <div class="line bottom"></div>
            </div>
        </li>

        <li class="logo hidden-xs">
            <a href="@Url.Action("index", "home")">MyD3 Schema Demo</a>
        </li>

        <li class="pull-right">
            <ul class="top-menu">
                <li id="toggle-width">
                    <div class="toggle-switch">
                        <input id="tw-switch" type="checkbox" hidden="hidden">
                        <label for="tw-switch" class="ts-helper"></label>
                    </div>
                </li>
                <li id="top-search">
                    <a class="tm-search" href=""></a>
                </li>
            </ul>
        </li>
    </ul>

    <!-- Top Search Content -->
    <div id="top-search-wrap">
        <input type="text">
        <i id="top-search-close">&times;</i>
    </div>
</header>

Code/MyD3/Views/Shared/Base/_LayoutProfileMenuPartial.cshtml
<div class="profile-menu">
    <a href="">
        <div class="profile-pic">
            <img src="" alt="">
        </div>

        <div class="profile-info">
            欢迎，<span class="login-user-name"></span>
            <i class="zmdi zmdi-arrow-drop-down"></i>
        </div>
    </a>

    <ul class="main-menu">
        <li>
            <a href="profile-about.html"><i class="zmdi zmdi-account"></i>查看个人资料</a>
        </li>
        <li>
            <a href='@Url.Action("logout", "index")'><i class="zmdi zmdi-time-restore"></i>注销</a>
        </li>
    </ul>
</div>

Code/MyD3/Views/Shared/Base/_LayoutSideMenuPartial.cshtml
<ul class="main-menu">
    <li class="mi_index"><a href="@Url.Action("index", "home")"><i class="zmdi zmdi-home"></i>首页</a></li>
    <li class="sub-menu mg_sys">
        <a href=""><i class="zmdi zmdi-settings"></i>系统模块</a>
        <ul>
            <li class="mi_user"><a href="@Url.Action("index", "User")">用户管理</a></li>
            <li class="mi_group"><a href="@Url.Action("index", "Group")">分组管理</a></li>
            <li class="mi_dictionary"><a href="@Url.Action("index", "Dictionary")">数据字典</a></li>
            <li class="mi_sysSetting"><a href="@Url.Action("index", "SystemSetting")">系统设置</a></li>
        </ul>
    </li>
</ul>